# Generated by Django 3.1.2 on 2020-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('note', models.CharField(max_length=800)),
                ('completion', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('Least Important', '✨ Least Important'), ('Somewhat Important', '⭐ Somewhat Important'), ('Mandatory', '🌟 Mandatory')], max_length=200, null=True)),
                ('Time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
