# Generated by Django 3.1.2 on 2020-11-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20201117_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
