# Generated by Django 3.1.2 on 2020-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20201117_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=800),
        ),
    ]
