# Generated by Django 3.1.2 on 2020-11-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_auto_20201118_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.IntegerField(default=0),
        ),
    ]
