# Generated by Django 3.1.2 on 2020-11-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20201118_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='important',
            new_name='prority',
        ),
    ]
