# Generated by Django 3.1.2 on 2020-11-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20201118_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='prority',
            new_name='priority',
        ),
    ]
