# Generated by Django 3.1.2 on 2020-11-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20201118_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Least Important'), ('2', 'Somewhat Important'), ('3', 'Mandatory')], max_length=200, null=True),
        ),
    ]
