# Generated by Django 3.1.2 on 2020-11-18 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_auto_20201118_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('1', 'ROSE'), ('2', 'BLUE'), ('3', 'YELLOW')], max_length=200, null=True)),
            ],
        ),
    ]
