# Generated by Django 3.1.2 on 2020-11-19 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
