# Generated by Django 3.1.2 on 2020-11-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0017_auto_20201119_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Least Important', '✨ 1'), ('Somewhat Important', '⭐ 2'), ('Mandatory', '🌟 3')], max_length=200, null=True),
        ),
    ]
